# Generated by Django 2.1.2 on 2018-12-12 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20181211_1658'),
        ('book', '0002_auto_20181210_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrower_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('returning_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('book_name', models.ManyToManyField(to='book.Book')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('pooled_users', models.ManyToManyField(blank=True, null=True, related_name='book_pooling_users', to='accounts.User')),
            ],
            options={
                'verbose_name_plural': 'Scheduling',
                'verbose_name': 'Scheduling',
            },
        ),
    ]
