# Generated by Django 2.1.2 on 2018-12-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower_detail',
            name='pooled_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_pooling_users', to='accounts.User'),
        ),
    ]
