# Generated by Django 2.1.2 on 2018-12-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_detail',
            name='fine',
        ),
    ]
