# Generated by Django 2.1.2 on 2018-12-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181210_1327'),
        ('events', '0002_remove_borrower_detail_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_detail',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='borrower_detail',
            name='book_name',
        ),
        migrations.AddField(
            model_name='borrower_detail',
            name='book_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='borrower_detail',
            name='pooled_users',
            field=models.ManyToManyField(related_name='book_pooling_users', to='accounts.User'),
        ),
    ]
