# Generated by Django 2.1.2 on 2018-12-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_borrower_detail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower_detail',
            old_name='title',
            new_name='borrowed_id',
        ),
    ]
