# Generated by Django 2.1.2 on 2018-12-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181212_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_detail',
            name='borrowed_id',
        ),
    ]
