# Generated by Django 2.1.2 on 2018-12-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181212_0906'),
        ('events', '0007_remove_borrower_detail_borrowed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_detail',
            name='book_name',
        ),
        migrations.AddField(
            model_name='borrower_detail',
            name='book_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
