# Generated by Django 2.1.2 on 2018-12-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181212_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower_detail',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
