# Generated by Django 2.1.2 on 2018-12-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181212_1008'),
        ('events', '0004_auto_20181212_0905'),
    ]

    operations = [
    ]
