# Generated by Django 2.1.2 on 2018-12-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_merge_20181212_1019'),
        ('events', '0002_auto_20181211_1658'),
    ]

    operations = [
    ]
