# Generated by Django 2.1.2 on 2018-12-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181211_2304'),
        ('book', '0004_merge_20181212_1150'),
        ('events', '0011_merge_20181212_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower_detail',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrower_detail',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='borrower_detail',
            name='submission_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='borrower_detail',
            unique_together={('name', 'book_name')},
        ),
    ]
