# Generated by Django 2.1.2 on 2018-11-18 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
