# Generated by Django 2.1.2 on 2018-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20181116_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description_view',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
