# Generated by Django 2.1.2 on 2018-11-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooled_token',
            name='token',
        ),
    ]
