# Generated by Django 2.1.2 on 2018-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='rdate',
            field=models.DateTimeField(),
        ),
    ]
