# Generated by Django 2.1.2 on 2018-11-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pooled_token',
            unique_together=set(),
        ),
    ]
