# Generated by Django 2.1.2 on 2018-12-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_auto_20181207_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user3',
        ),
    ]
