# Generated by Django 2.1.2 on 2018-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_auto_20181211_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='rdate',
            field=models.DateTimeField(null=True),
        ),
    ]
