# Generated by Django 2.1.2 on 2018-11-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0003_pooled_token_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token',
        ),
    ]
