# Generated by Django 2.1.2 on 2018-12-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0003_auto_20181211_1830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
    ]
