# Generated by Django 2.1.2 on 2018-12-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('borrower', '0003_auto_20181207_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='token',
            name='user3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user3', to='accounts.User'),
        ),
    ]
