# Generated by Django 2.1.2 on 2018-11-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0004_remove_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
