# Generated by Django 2.1.2 on 2018-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0004_auto_20181207_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.IntegerField(unique=True),
        ),
    ]
