# Generated by Django 2.1.2 on 2018-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0005_auto_20181208_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='rdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
