# Generated by Django 2.1.2 on 2018-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0007_auto_20181208_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='rdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
