# Generated by Django 2.1.2 on 2018-11-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('last_logged_in', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(blank=True, choices=[('General', 'General'), ('User', 'User'), ('Student', 'Student')], max_length=6, null=True)),
                ('book_issued', models.ManyToManyField(to='book.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
