<<<<<<< HEAD
# Generated by Django 2.1.2 on 2018-11-18 12:00
=======
# Generated by Django 2.1.2 on 2018-11-18 13:17
>>>>>>> 63cbeee74ffeebb9aff3e037ca595205d18d4ecf

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='abc',
        ),
    ]
