# Generated by Django 2.1.2 on 2018-11-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181110_2020'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book_issed',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
