# Generated by Django 2.1.2 on 2018-11-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_logged_in',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=6, null=True),
        ),
    ]
