# Generated by Django 2.1.2 on 2018-11-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_book_issed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='book_issed',
            new_name='book_issued',
        ),
    ]
