# Generated by Django 2.1.2 on 2018-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181114_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book_issued',
            field=models.ManyToManyField(blank=True, null=True, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
