# Generated by Django 2.1.2 on 2018-12-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='file',
        ),
    ]
