# Generated by Django 2.1.2 on 2018-12-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='File',
        ),
    ]
