# Generated by Django 2.1.2 on 2018-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181115_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book_issued',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
