# Generated by Django 2.1.2 on 2018-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181115_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book_issued',
            field=models.ManyToManyField(blank=True, to='book.Book'),
        ),
    ]
