# Generated by Django 2.1.2 on 2018-11-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='products',
            new_name='books',
        ),
    ]
