# Generated by Django 2.1.2 on 2018-11-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat1books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='borrower_detail',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cat1books.User'),
        ),
        migrations.AlterField(
            model_name='borrower_detail',
            name='pooled_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_pooling_users', to='cat1books.User'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat1books.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat1books.User'),
        ),
        migrations.AddField(
            model_name='token',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat1books.User'),
        ),
    ]
