# Generated by Django 2.1.2 on 2018-11-11 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat1books', '0004_auto_20181111_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
