# Generated by Django 2.1.2 on 2018-11-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat1books', '0005_auto_20181111_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat1books.Request'),
        ),
    ]
