# Generated by Django 2.1.2 on 2018-11-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cat1books', '0006_auto_20181115_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='book_name',
            field=models.ForeignKey(default=0.09090909090909091, on_delete=django.db.models.deletion.CASCADE, to='cat1books.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrower_detail',
            name='name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='borrower_detail',
            name='pooled_users',
            field=models.ManyToManyField(blank=True, related_name='book_pooling_users', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='book_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat1books.Book'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user_name', 'book_name')},
        ),
    ]
