# Generated by Django 2.1.2 on 2018-12-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=40)),
                ('comments', models.TextField()),
                ('book_name', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
