# Generated by Django 2.1.2 on 2018-11-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='name',
            new_name='title',
        ),
    ]
