# Generated by Django 2.1.2 on 2018-11-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181116_1252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='token',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='token',
        ),
    ]
