# Generated by Django 2.1.2 on 2018-12-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181211_1218'),
        ('book', '0002_auto_20181210_1327'),
    ]

    operations = [
    ]
