# Generated by Django 2.1.2 on 2018-12-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181212_0906'),
        ('book', '0002_auto_20181210_1327'),
    ]

    operations = [
    ]
