# Generated by Django 2.1.2 on 2018-12-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_merge_20181212_1019'),
        ('book', '0003_merge_20181211_1259'),
    ]

    operations = [
    ]
