# Generated by Django 2.1.2 on 2018-11-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20181116_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un', to='accounts.User', unique=True),
        ),
    ]
