# Generated by Django 2.1.2 on 2018-11-17 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20181116_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
