# Generated by Django 2.1.2 on 2018-11-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='mail_from',
            field=models.CharField(default='webmaster@localhost', max_length=200),
        ),
    ]
