# Generated by Django 2.1.2 on 2018-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='mail_from',
            field=models.CharField(default='rehanmallick4080@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='mail_replyto',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
