# Generated by Django 2.1.2 on 2018-12-11 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronta', '0004_auto_20181211_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='scheduled_datetime',
            field=models.DateField(default=datetime.date(2018, 12, 11), verbose_name='send_time'),
        ),
    ]
