# Generated by Django 2.1.2 on 2018-12-11 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cronta', '0008_auto_20181211_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='scheduled_datetime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='send_time'),
        ),
    ]
