# Generated by Django 2.1.2 on 2018-12-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronta', '0002_auto_20181211_1712'),
        ('cronta', '0009_auto_20181211_1733'),
    ]

    operations = [
    ]
